version: "3.7"
services:
  api:
    build: "./api"
    ports:
      - "2000:80"
    networks:
      - multistagenet
  web:
    build:
      context: "./web"
      target: production
    ports:
      - "2001:80"
    networks:
      - multistagenet
networks:
  multistagenet:
