version: "3.7"
services:
  api:
    build: "./api"
    ports:
      - "2000:80"
    networks:
      - multistagenet
  web:
    build:
      context: "./web"
      target: development
    ports:
      - "8089:8080"
    volumes:
      - ./web/app:/app
      - node_modules:/app/node_modules
    networks:
      - multistagenet

volumes:
  node_modules:

networks:
  multistagenet:

